<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-15 at 11:28:23.
 */
// class CDQuestionnaireTest extends PHPUnit_Framework_TestCase
class CDQuestionnaireTest extends PHPUnit_Extensions_Database_TestCase {
	/**
	 *
	 * @var CDQuestionnaire
	 */
	protected $object;
	
	// PDO のインスタンス生成は、クリーンアップおよびフィクスチャ読み込みのときに一度だけ
	private static $pdo = null;
	
	// PHPUnit_Extensions_Database_DB_IDatabaseConnection のインスタンス生成は、テストごとに一度だけ
	private $conn = null;
	final public function getConnection() {
		if ($this->conn === null) {
			if (self::$pdo == null) {
				self::$pdo = new PDO ( $GLOBALS ['DB_DSN'], $GLOBALS ['DB_USER'], $GLOBALS ['DB_PASSWD'] );
			}
			$this->conn = $this->createDefaultDBConnection ( self::$pdo, $GLOBALS ['DB_DBNAME'] );
		}
		
		return $this->conn;
	}
	
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new CDQuestionnaire ();
	}
	
	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}
	
	/**
	 * @covers CDQuestionnaire::add_pages
	 * 
	 * @todo Implement testAdd_pages().
	 */
	public function testAdd_pages() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete ( 'This test has not been implemented yet.' );
	}
	
	/**
	 * @covers CDQuestionnaire::questionnaire_option_page
	 * 
	 * @todo Implement testQuestionnaire_option_page().
	 */
	public function testQuestionnaire_option_page() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete ( 'This test has not been implemented yet.' );
	}
	
	/**
	 * @covers CDQuestionnaire::activate
	 * 
	 * @todo Implement testActivate().
	 */
	public function testActivate() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete ( 'This test has not been implemented yet.' );
	}
	
	/**
	 * @covers CDQuestionnaire::enquetesSql
	 * 
	 * @todo Implement testEnquetesSql().
	 */
	public function testEnquetesSql() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete ( 'This test has not been implemented yet.' );
	}
	
	/**
	 * @covers CDQuestionnaire::questionsSql
	 * 
	 * @todo Implement testQuestionsSql().
	 */
	public function testQuestionsSql() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete ( 'This test has not been implemented yet.' );
	}
	
	/**
	 * @covers CDQuestionnaire::selectionsSql
	 * 
	 * @todo Implement testSelectionsSql().
	 */
	public function testSelectionsSql() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete ( 'This test has not been implemented yet.' );
	}
	
	/**
	 * @covers CDQuestionnaire::answersSql
	 * 
	 * @todo Implement testAnswersSql().
	 */
	public function testAnswersSql() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete ( 'This test has not been implemented yet.' );
	}
	
	/**
	 * @covers CDQuestionnaire::identifiersSql
	 * 
	 * @todo Implement testIdentifiersSql().
	 */
	public function testIdentifiersSql() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete ( 'This test has not been implemented yet.' );
	}
	
	/**
	 * @covers CDQuestionnaire::questionnaire
	 * 
	 * @todo Implement testQuestionnaire().
	 */
	public function testQuestionnaire() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete ( 'This test has not been implemented yet.' );
	}
}
